### ISSUE TITLE
SLF4J dependencies are not properly set

### ISSUE THREAD

**Issue by mstahv** [vaadin/framework8-migration-tool#11]
The log outputs:

    SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder

**Comment by javydreamercsw** [comment]
I get the same error.

**Comment by mvysny** [comment]
I've fixed this in https://github.com/mvysny/framework8-migration-tool/commit/92e6afb26128f2fed9e31f4f8026336264816e2a by adding the slf4j-simple logger.

**Comment by Artur-** [comment]
Fixed in #43
