### ISSUE TITLE
Can't open design files in Vaadin Designer 2 after running tool

### ISSUE THREAD

**Issue by fakeh** [vaadin/framework8-migration-tool#12]
Hi,
It would be nice to be able to open Vaadin Designer 1 files in version 2 after running this tool.
Dan.

**Comment by Artur-** [comment]
Hi, what is the problem you are experiencing? The files should be converted and Designer 2 should open them as long as you change the project to use Vaadin 8.x

**Comment by fakeh** [comment]
Hi Artur, 
After running the tool, the tags are updated to use vaadin7 ones, but the design files cannot be opened in Designer 2 without a manual change to each design file, <meta name="vaadin-version" content="8.0.0.beta1">. I'd suggest that this could be automated by the tool as well.
Dan.

**Comment by alejandro-du** [comment]
Duplicated. See #8.

**Comment by nordligulv** [comment]
That's correct. The Designer cannot open converted html file because it still contains meta tag with vaadin 7 version. @Artur- Could you just remove it at all or update content to the used vaadin 8 version?

**Comment by hesara** [comment]
Fixed by #13.
