### ISSUE TITLE
Encoding problem after upgrading project

### ISSUE THREAD

**Issue by WB286** [vaadin/framework8-migration-tool#24]
After upgrading a vaadin-7 project with ''mvn vaadin:upgrade8" all special letters were replaced with the '?' sign.

For example:
`private LocalDate maßgeblichesDatum;`
got changed into:
`private LocalDate ma?geblichesDatum;`

Also the letters ö, ä, ü and ß were replaced by the question mark in the comment sections:
`/* Geschäftspartner */`
got changed into:
`/* Gesch?ftspartner */`

The file encoding was "ISO-8859-1".

**Comment by ste-bo** [comment]
I noticed something similiar for newlines. It seems, that the tool replaces <CR><LF> with <LF> in the upgraded files.

**Comment by ropoman** [comment]
+1 for this issue

**Comment by RobertZenz** [comment]
Yes, I just had the same issue, the encoding of the files that are processed are not correctly handled. Unfortunately, I can't share my fix/patch until #34 is resolved.
