### ISSUE TITLE
Dependency cannot be resolved

### ISSUE THREAD

**Issue by joekienzle** [vaadin/framework8-migration-tool#32]
I was trying to use the migration tool to upgrade our vaadin project. I installed the migration tool to my local repository and then tried to use
`mvn vaadin:upgrade8` and get the following stacktrace: [https://pastebin.com/7vy3Tr87](https://pastebin.com/7vy3Tr87)

We are using a local artifactory and are behind a proxy. It seems strange that the tool tries to download dependencies and seems to not care for my `~/.m2/settings.xml` where my proxy and artifactory are configured. How do I solve this issue?

**Comment by hesara** [comment]
As this is a standalone tool (triggerable from Maven), it does not run in the context of the Maven process. Thus, respecting local settings files would probably require either the Maven process passing a list of effective repositories to the migration process, or the migration process reading the settings files, perhaps like http://stackoverflow.com/questions/27818659/loading-mavens-settings-xml-for-jcabi-aether-to-use .

Unfortunately, both approaches require code changes in the migration tool, so the quickest workaround for you to get forward would probably be to edit, compile and run a local version of the migration tool with your list of repositories.

**Comment by joekienzle** [comment]
Alright thank you, I modified the code this way so it works for us now:

```
public class MavenResolver {
    private static final RepositorySystem repoSystem = createServiceLocator()
            .getService(RepositorySystem.class);
    private static final List<RemoteRepository> repositories = Collections.singletonList(
            new RemoteRepository.Builder("ahuInternal", "default",
                    "http://ourRepository:8081/").build());
```
